### ISSUE TITLE
Support https endpoints?

### ISSUE THREAD

**Issue by techdaddies-kevin** [Xon/XenForo-SearchImprovements#1]
Would it be possible for this to be updated to support an https endpoint? Out of the box, XF forces the endpoint to be http which is problematic for most hosted ES services like AWS ElasticSearch. I had planned on digging into the XF source this weekend to investigate, and that's when I came across this addon. If this could be extended to support that use case, it would be great because I actually want to use all of the features that this addon offers as well. This is a 32M post forum and some power users want access to even more than the stock Enhanced Search offers.

**Comment by Xon** [comment]
This wasn't hard to implement; can you try https://github.com/Xon/XenForo-SearchImprovements/archive/1.3.x.zip

There should be a new checkbox "https" on the Search Options page for the ElasticSearch options.

Technically it backports username/password support, but I couldn't be bothered wiring up the UI since this was very quick.

Sadly; you'll still need to reconfigure XF2's Elasticsearch on upgrading to re-enable HTTPS support. Annoying, but easy to manage.

**Comment by techdaddies-kevin** [comment]
Nice. Code changes look like they should work perfectly. We just now acquired this site and they are currently running XenES 1.1.2 and XF 1.4.7 (Old, I know. It's on the list to update). When I try to install the addon, I get a 500 error. Logs show: 

```ErrorException: Fatal Error: Uncaught TypeError: Argument 1 passed to XenForo_Application::handleException() must be an instance of Exception, instance of Error given in /home/site/public/library/XenForo/Application.php:375 Stack trace: #0 [internal function]: XenForo_Application::handleException(Object(Error)) #1 {main} thrown - library/XenForo/Application.php:375```

Do you think this is being caused by the old versions? If so, we'll just need to upgrade before utilizing this add-on.

Thanks Xon.

**Comment by Xon** [comment]
Need a stack-trace, as the top-level error just isn't useful. Something is trying to log an error, but the logging is then failing eating the original error.

My rough guess is you are running php 7.x, which requires XF 1.5.something to work properly.

**Comment by techdaddies-kevin** [comment]
You're exactly right. Downgraded to 5.6 and it installed fine. Looks good. See the checkbox. Will launch a test ES server tomorrow and attempt to access it from XF but it looks like it's going to work.

Thanks!

**Comment by techdaddies-kevin** [comment]
I got this installed and configured today and it seemed to be connecting to the server fine. However, when I tried to rebuild the search index, I got an error.

```
XenForo_Exception: No response returned from Elasticsearch. Is it running? - library/XenES/Search/SourceHandler/ElasticSearch.php:971

#0 /home/adv/public/library/XenES/Search/SourceHandler/ElasticSearch.php(76): XenES_Search_SourceHandler_ElasticSearch->_triggerFailedIndexError(false, Array)
#1 /home/adv/public/library/XenForo/Search/Indexer.php(125): XenES_Search_SourceHandler_ElasticSearch->finalizeRebuildSet()
#2 /home/adv/public/library/XenForo/Deferred/SearchIndex.php(74): XenForo_Search_Indexer->finalizeRebuildSet()
#3 /home/adv/public/library/XenForo/Model/Deferred.php(294): XenForo_Deferred_SearchIndex->execute(Array, Array, 7.9258770942688, '')
#4 /home/adv/public/library/XenForo/Model/Deferred.php(428): XenForo_Model_Deferred->runDeferred(Array, 7.9258770942688, '', false)
#5 /home/adv/public/library/XenForo/Model/Deferred.php(373): XenForo_Model_Deferred->_runInternal(Array, 7.9258780479431, '', false)
#6 /home/adv/public/library/XenForo/ViewRenderer/Abstract.php(352): XenForo_Model_Deferred->run(true, 7.9258780479431)
#7 /home/adv/public/library/XenForo/ViewRenderer/Json.php(147): XenForo_ViewRenderer_Abstract::hasManualDeferredToRun()
#8 /home/adv/public/library/XenForo/ViewRenderer/Json.php(185): XenForo_ViewRenderer_Json::_addDefaultParams(Array)
#9 /home/adv/public/library/XenForo/ViewRenderer/Json.php(61): XenForo_ViewRenderer_Json::jsonEncodeForOutput(Array)
#10 /home/adv/public/library/XenForo/FrontController.php(574): XenForo_ViewRenderer_Json->renderError('No response ret...')
#11 /home/adv/public/library/XenForo/FrontController.php(158): XenForo_FrontController->renderView(Object(XenForo_ControllerResponse_Error), Object(XenForo_ViewRenderer_Json), Array)
#12 /home/adv/public/admin.php(13): XenForo_FrontController->run()
#13 {main}
```

When I disabled this addon and hardcoded the https in the XenES/Api.php class, rebuilding the search index worked fine.

**Comment by Xon** [comment]
Can you give the latest head of the 1.3.x branch a try? It should now load the https-enabled class when indexing.

**Comment by techdaddies-kevin** [comment]
Finally got the site moved over to our hardware. Running latest version of XF, XFES, latest HEAD of this repo, and ES 6.2. Attempted to rebuild search index and received:

```
Invalid model 'SV_ElasticEss_Model' specified

XenForo_Model::create() in XenForo/Model.php at line 113
XenForo_Model->getModelFromCache() in SV/SearchImprovements/XenES/Model/Elasticsearch.php at line 167
SV_SearchImprovements_XenES_Model_Elasticsearch->recreateIndex() in XenES/Search/SourceHandler/ElasticSearch.php at line 159
XenES_Search_SourceHandler_ElasticSearch->deleteIndex() in XenForo/Deferred/SearchIndex.php at line 62
XenForo_Deferred_SearchIndex->execute() in XenForo/Model/Deferred.php at line 295
XenForo_Model_Deferred->runDeferred() in XenForo/Model/Deferred.php at line 429
XenForo_Model_Deferred->_runInternal() in XenForo/Model/Deferred.php at line 374
XenForo_Model_Deferred->run() in XenForo/ControllerAdmin/Tools.php at line 159
XenForo_ControllerAdmin_Tools->actionRunDeferred() in XenForo/FrontController.php at line 369
XenForo_FrontController->dispatch() in XenForo/FrontController.php at line 152
XenForo_FrontController->run() in /home/adv/public/admin.php at line 13
```

**Comment by techdaddies-kevin** [comment]
Same error occurs when I disable the addon, as well.

**Comment by Xon** [comment]
@techdaddies-kevin should be fixed now, can you grab the latest of the master branch again?

**Comment by techdaddies-kevin** [comment]
Beautiful, thanks!

I will try to get the owner to purchase the SearchEssentials addon ASAP. Looks like it adds a lot of useful features.
